### ISSUE TITLE
SLF4J provider name has no package prefix

### ISSUE THREAD

**Issue by ceki** [jstachio/rainbowgum#174]
The line in question is referenced below:

https://github.com/jstachio/rainbowgum/blob/1ce7792dbf7fcfd16ad98841540bff661d4c9d49/rainbowgum-slf4j/src/main/java/module-info.java#L51

**Comment by agentgt** [comment]
I know that is a problem with moditect but how is it a problem with normal javac?

**Comment by agentgt** [comment]
Don't ask Chat GPT because its wrong and will say its not allowed.

This SO post covers it: https://stackoverflow.com/questions/60267177/module-descriptor-file-allowed-import-statements-why

However given various hackish tools that do parsing like moditect I can change it and probably should.

**Comment by agentgt** [comment]
@ceki happy to put the FQN explicitly but would like to know which tool is failing for you.

Also we test jlink which is pretty much the authority on `module-info` correctness on every build and it appears to be fine with that module: https://github.com/jstachio/rainbowgum/blob/main/test/rainbowgum-test-jlink/pom.xml

I think how it happened is there was a javadoc reference and it got removed.

**Comment by ceki** [comment]
My apologies had not seen the import statement. I was using my eyes as the verification tool.

**Comment by agentgt** [comment]
@ceki let me know if you have any questions. Some of the SLF4J modules code is auto generated but it doesn't do it on build. The rainbowgum-slf4j module is particularly nasty because it was one of the first written.

Also while it may appear Rainbow Gum is a competitor to logback it is not but rather experimenting future JDK features/design that I hope logback can use so I'm thrilled your taking a look (as well as humbled).
